### ISSUE TITLE
Not working on local domain

### ISSUE THREAD

**Issue by umitatestr** [elmahio-blog/Elmah.Blog.ImageProcessorWebP#1]
Hello there,
I downloaded your sample project. I ran it locally using Visual Studio using IIS Express in debug mode. I made the process of converting the pictures to WEBP format by updating them. No problem so far.

I included your codes in my project that I am currently working on.

When I debug my project via IIS Express, the upload and conversion process was successful.

The problem begins now; My local project is also registered as a domain to IIS and I am doing my improvements in this way (such as domain.local). But it saves the original image I want to upload, but it gives the following error in the webp conversion process.

Error;
{"The type initializer for 'ImageProcessor.Plugins.WebP.Imaging.Formats.NativeMethods' threw an exception."}
{"Cannot load libwebp.dll"}

My project is Asp.Net Core 2.2 web application.

I would be glad if there is anything you can help.

**Comment by KristofferStrube** [comment]
Hey,

It seems that others have had a similar problem when using ImageProcessor.Plugins.WebP as it can be seen here: https://github.com/JimBobSquarePants/ImageProcessor/issues/764

The documentation for ImageProcessor states: 
> Requires msvcr120.dll from the [Visual C++ Redistributable Package for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784) to be installed on the server.

This could be why it works locally for you but not when you host it through IIS.

Hope this helps.

**Comment by umitatestr** [comment]
I found the answers you sent in my researches, and since there was no solution, I needed to write here.

Sample; The application does its job without error while working with IIS Express. But when the application is defined to IIS it gives an error. I even published this sample project and when I defined the publish folder to IIS and run it, the sample still worked fine.

This application is working in IIS express and after publishing. But when I want to define and run the project to IIS during development, WEBP gives the error in the first message in the conversion process.

These things are related to the solution you suggested. What do you think?

**Comment by ThomasArdal** [comment]
I don't think that this is the right forum for questions around WEBP, etc. This is simply our sample code for a blog post we wrote. Maybe move the conversation to StackOverflow?
